/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import clases.Administrador;
import clases.Cola;
import clases.Funciones;
import clases.IA;
import clases.Vehiculo;
import java.util.concurrent.Semaphore;

/**
 *
 * @author juanc
 */
public class Pantalla extends javax.swing.JFrame {

    public Semaphore mutex;
    public int segundos;
    
    public Cola lambo_p1;
    public Cola lambo_p2;
    public Cola lambo_p3;
    public Cola lambo_r;
    
    public Cola bugatti_p1;
    public Cola bugatti_p2;
    public Cola bugatti_p3;
    public Cola bugatti_r;
    
    public Vehiculo lamborghini;
    public Vehiculo bugatti; 
    
    public Pantalla() {
        initComponents();
        addComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Fondo = new Pantallas.BackgroundPanel();
        header = new javax.swing.JPanel();
        roundedPanel1 = new Pantallas.RoundedPanel();
        title = new javax.swing.JLabel();
        left = new javax.swing.JPanel();
        roundedPanel3 = new Pantallas.RoundedPanel();
        lamboP1Label = new javax.swing.JLabel();
        lamboP1 = new javax.swing.JTextField();
        lamboP2Label = new javax.swing.JLabel();
        lamboP2 = new javax.swing.JTextField();
        lamboP3Label = new javax.swing.JLabel();
        lamboP3 = new javax.swing.JTextField();
        lamboRLabel = new javax.swing.JLabel();
        lamboR = new javax.swing.JTextField();
        body = new javax.swing.JPanel();
        roundedPanel2 = new Pantallas.RoundedPanel();
        bugattiImg = new javax.swing.JLabel();
        lamboImg = new javax.swing.JLabel();
        idLambo = new javax.swing.JLabel();
        idBugatti = new javax.swing.JLabel();
        estadoL = new javax.swing.JLabel();
        estadoB = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pistaImg = new javax.swing.JLabel();
        timeL = new javax.swing.JLabel();
        timeB = new javax.swing.JLabel();
        estadoIA = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        roundedPanel4 = new Pantallas.RoundedPanel();
        bugattiP1Label = new javax.swing.JLabel();
        bugattiP1 = new javax.swing.JTextField();
        bugattiP2Label = new javax.swing.JLabel();
        bugattiP2 = new javax.swing.JTextField();
        bugattiP3Label = new javax.swing.JLabel();
        bugattiP3 = new javax.swing.JTextField();
        bugattiRLabel = new javax.swing.JLabel();
        bugattiR = new javax.swing.JTextField();
        footer = new javax.swing.JPanel();
        Slider = new javax.swing.JSlider();
        SliderLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelGanadoresBugatti = new javax.swing.JLabel();
        labelGanadoresLambo = new javax.swing.JLabel();
        nroGanadoresBugatti = new javax.swing.JLabel();
        nroGanadoresLambo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        colaGanadores = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulación");
        setResizable(false);

        header.setOpaque(false);
        header.setPreferredSize(new java.awt.Dimension(1000, 100));
        header.setLayout(new java.awt.GridBagLayout());

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(500, 80));

        title.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Lamborghini VS Bugatti");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roundedPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(title)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roundedPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(title)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        header.add(roundedPanel1, new java.awt.GridBagConstraints());

        left.setOpaque(false);
        left.setPreferredSize(new java.awt.Dimension(300, 400));
        left.setLayout(new java.awt.GridBagLayout());

        roundedPanel3.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel3.setPreferredSize(new java.awt.Dimension(250, 350));
        roundedPanel3.setLayout(new java.awt.GridBagLayout());

        lamboP1Label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lamboP1Label.setForeground(new java.awt.Color(0, 0, 0));
        lamboP1Label.setText("Prioridad Alta");
        lamboP1Label.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 5, 5));
        roundedPanel3.add(lamboP1Label, new java.awt.GridBagConstraints());

        lamboP1.setEditable(false);
        lamboP1.setBackground(new java.awt.Color(255, 255, 255));
        lamboP1.setColumns(12);
        lamboP1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lamboP1.setForeground(new java.awt.Color(0, 0, 0));
        lamboP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lamboP1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        roundedPanel3.add(lamboP1, gridBagConstraints);

        lamboP2Label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lamboP2Label.setForeground(new java.awt.Color(0, 0, 0));
        lamboP2Label.setText("Prioridad Media");
        lamboP2Label.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 5, 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        roundedPanel3.add(lamboP2Label, gridBagConstraints);

        lamboP2.setEditable(false);
        lamboP2.setBackground(new java.awt.Color(255, 255, 255));
        lamboP2.setColumns(12);
        lamboP2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lamboP2.setForeground(new java.awt.Color(0, 0, 0));
        lamboP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lamboP2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        roundedPanel3.add(lamboP2, gridBagConstraints);

        lamboP3Label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lamboP3Label.setForeground(new java.awt.Color(0, 0, 0));
        lamboP3Label.setText("Prioridad Baja");
        lamboP3Label.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 5, 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        roundedPanel3.add(lamboP3Label, gridBagConstraints);

        lamboP3.setEditable(false);
        lamboP3.setBackground(new java.awt.Color(255, 255, 255));
        lamboP3.setColumns(12);
        lamboP3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lamboP3.setForeground(new java.awt.Color(0, 0, 0));
        lamboP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lamboP3.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        roundedPanel3.add(lamboP3, gridBagConstraints);

        lamboRLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lamboRLabel.setForeground(new java.awt.Color(0, 0, 0));
        lamboRLabel.setText("Refuerzo");
        lamboRLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 5, 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        roundedPanel3.add(lamboRLabel, gridBagConstraints);

        lamboR.setEditable(false);
        lamboR.setBackground(new java.awt.Color(255, 255, 255));
        lamboR.setColumns(12);
        lamboR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lamboR.setForeground(new java.awt.Color(0, 0, 0));
        lamboR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lamboR.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        roundedPanel3.add(lamboR, gridBagConstraints);

        left.add(roundedPanel3, new java.awt.GridBagConstraints());

        body.setOpaque(false);
        body.setPreferredSize(new java.awt.Dimension(400, 400));
        body.setLayout(new java.awt.GridBagLayout());

        roundedPanel2.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel2.setPreferredSize(new java.awt.Dimension(350, 350));

        idLambo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        idLambo.setForeground(new java.awt.Color(0, 0, 0));
        idLambo.setText("L0");

        idBugatti.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        idBugatti.setForeground(new java.awt.Color(0, 0, 0));
        idBugatti.setText("B0");

        estadoL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        estadoL.setForeground(new java.awt.Color(0, 0, 0));
        estadoL.setText("Estado");

        estadoB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        estadoB.setForeground(new java.awt.Color(0, 0, 0));
        estadoB.setText("Estado");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pistaImg.setPreferredSize(new java.awt.Dimension(200, 90));
        jPanel1.add(pistaImg, new java.awt.GridBagConstraints());

        timeL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        timeL.setForeground(new java.awt.Color(0, 0, 0));
        timeL.setText("00:00");

        timeB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        timeB.setForeground(new java.awt.Color(0, 0, 0));
        timeB.setText("00:00");

        estadoIA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        estadoIA.setForeground(new java.awt.Color(0, 0, 0));
        estadoIA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lamboImg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bugattiImg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel2Layout.createSequentialGroup()
                        .addComponent(estadoL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estadoB))
                    .addGroup(roundedPanel2Layout.createSequentialGroup()
                        .addComponent(idLambo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idBugatti)))
                .addGap(81, 81, 81))
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roundedPanel2Layout.createSequentialGroup()
                        .addComponent(timeL)
                        .addGap(18, 18, 18)
                        .addComponent(estadoIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(timeB))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lamboImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bugattiImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLambo)
                    .addComponent(idBugatti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estadoL)
                    .addComponent(estadoB))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timeL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estadoIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        body.add(roundedPanel2, new java.awt.GridBagConstraints());

        right.setOpaque(false);
        right.setPreferredSize(new java.awt.Dimension(300, 400));
        right.setLayout(new java.awt.GridBagLayout());

        roundedPanel4.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel4.setPreferredSize(new java.awt.Dimension(250, 350));
        roundedPanel4.setLayout(new java.awt.GridBagLayout());

        bugattiP1Label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bugattiP1Label.setForeground(new java.awt.Color(0, 0, 0));
        bugattiP1Label.setText("Prioridad Alta");
        bugattiP1Label.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 5, 5));
        roundedPanel4.add(bugattiP1Label, new java.awt.GridBagConstraints());

        bugattiP1.setEditable(false);
        bugattiP1.setBackground(new java.awt.Color(255, 255, 255));
        bugattiP1.setColumns(12);
        bugattiP1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bugattiP1.setForeground(new java.awt.Color(0, 0, 0));
        bugattiP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bugattiP1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        roundedPanel4.add(bugattiP1, gridBagConstraints);

        bugattiP2Label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bugattiP2Label.setForeground(new java.awt.Color(0, 0, 0));
        bugattiP2Label.setText("Prioridad Media");
        bugattiP2Label.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 5, 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        roundedPanel4.add(bugattiP2Label, gridBagConstraints);

        bugattiP2.setEditable(false);
        bugattiP2.setBackground(new java.awt.Color(255, 255, 255));
        bugattiP2.setColumns(12);
        bugattiP2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bugattiP2.setForeground(new java.awt.Color(0, 0, 0));
        bugattiP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bugattiP2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        roundedPanel4.add(bugattiP2, gridBagConstraints);

        bugattiP3Label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bugattiP3Label.setForeground(new java.awt.Color(0, 0, 0));
        bugattiP3Label.setText("Prioridad Baja");
        bugattiP3Label.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 5, 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        roundedPanel4.add(bugattiP3Label, gridBagConstraints);

        bugattiP3.setEditable(false);
        bugattiP3.setBackground(new java.awt.Color(255, 255, 255));
        bugattiP3.setColumns(12);
        bugattiP3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bugattiP3.setForeground(new java.awt.Color(0, 0, 0));
        bugattiP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bugattiP3.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        roundedPanel4.add(bugattiP3, gridBagConstraints);

        bugattiRLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bugattiRLabel.setForeground(new java.awt.Color(0, 0, 0));
        bugattiRLabel.setText("Refuerzo");
        bugattiRLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 5, 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        roundedPanel4.add(bugattiRLabel, gridBagConstraints);

        bugattiR.setEditable(false);
        bugattiR.setBackground(new java.awt.Color(255, 255, 255));
        bugattiR.setColumns(12);
        bugattiR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bugattiR.setForeground(new java.awt.Color(0, 0, 0));
        bugattiR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bugattiR.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        roundedPanel4.add(bugattiR, gridBagConstraints);

        right.add(roundedPanel4, new java.awt.GridBagConstraints());

        footer.setOpaque(false);
        footer.setPreferredSize(new java.awt.Dimension(1000, 100));

        Slider.setBackground(new java.awt.Color(255, 255, 255));
        Slider.setMaximum(20);
        Slider.setMinimum(1);
        Slider.setValue(10);
        Slider.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        Slider.setOpaque(true);
        Slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderStateChanged(evt);
            }
        });

        SliderLabel.setBackground(new java.awt.Color(255, 255, 255));
        SliderLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SliderLabel.setForeground(new java.awt.Color(255, 255, 255));
        SliderLabel.setText("Velocidad");
        SliderLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 6, 6));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ganadores:");

        labelGanadoresBugatti.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelGanadoresBugatti.setForeground(new java.awt.Color(0, 0, 0));
        labelGanadoresBugatti.setText("Bugatti:");

        labelGanadoresLambo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelGanadoresLambo.setForeground(new java.awt.Color(0, 0, 0));
        labelGanadoresLambo.setText("Lamborghini:");

        nroGanadoresBugatti.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nroGanadoresBugatti.setForeground(new java.awt.Color(0, 0, 0));
        nroGanadoresBugatti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nroGanadoresBugatti.setText("0");
        nroGanadoresBugatti.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        nroGanadoresLambo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nroGanadoresLambo.setForeground(new java.awt.Color(0, 0, 0));
        nroGanadoresLambo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nroGanadoresLambo.setText("0");
        nroGanadoresLambo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelGanadoresLambo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelGanadoresBugatti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nroGanadoresBugatti, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(nroGanadoresLambo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGanadoresBugatti)
                    .addComponent(nroGanadoresBugatti, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelGanadoresLambo)
                    .addComponent(nroGanadoresLambo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cola de ganadores:");

        colaGanadores.setEditable(false);
        colaGanadores.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(colaGanadores))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 154, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colaGanadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(footerLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(SliderLabel))
                    .addComponent(Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(footerLayout.createSequentialGroup()
                        .addComponent(SliderLabel)
                        .addGap(0, 0, 0)
                        .addComponent(Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderStateChanged
        this.segundos = this.Slider.getValue();
    }//GEN-LAST:event_SliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Pantallas.BackgroundPanel Fondo;
    private javax.swing.JSlider Slider;
    private javax.swing.JLabel SliderLabel;
    private javax.swing.JPanel body;
    private javax.swing.JLabel bugattiImg;
    private javax.swing.JTextField bugattiP1;
    private javax.swing.JLabel bugattiP1Label;
    private javax.swing.JTextField bugattiP2;
    private javax.swing.JLabel bugattiP2Label;
    private javax.swing.JTextField bugattiP3;
    private javax.swing.JLabel bugattiP3Label;
    private javax.swing.JTextField bugattiR;
    private javax.swing.JLabel bugattiRLabel;
    public javax.swing.JTextField colaGanadores;
    public javax.swing.JLabel estadoB;
    public javax.swing.JLabel estadoIA;
    public javax.swing.JLabel estadoL;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    public javax.swing.JLabel idBugatti;
    public javax.swing.JLabel idLambo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelGanadoresBugatti;
    private javax.swing.JLabel labelGanadoresLambo;
    private javax.swing.JLabel lamboImg;
    private javax.swing.JTextField lamboP1;
    private javax.swing.JLabel lamboP1Label;
    private javax.swing.JTextField lamboP2;
    private javax.swing.JLabel lamboP2Label;
    private javax.swing.JTextField lamboP3;
    private javax.swing.JLabel lamboP3Label;
    private javax.swing.JTextField lamboR;
    private javax.swing.JLabel lamboRLabel;
    private javax.swing.JPanel left;
    public javax.swing.JLabel nroGanadoresBugatti;
    public javax.swing.JLabel nroGanadoresLambo;
    public javax.swing.JLabel pistaImg;
    private javax.swing.JPanel right;
    private Pantallas.RoundedPanel roundedPanel1;
    private Pantallas.RoundedPanel roundedPanel2;
    private Pantallas.RoundedPanel roundedPanel3;
    private Pantallas.RoundedPanel roundedPanel4;
    public javax.swing.JLabel timeB;
    public javax.swing.JLabel timeL;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private void addComponents() {
        this.setLocationRelativeTo(null);
        Funciones.setWindowIcon(this, "logo.jpg");
        Funciones.scaleImage(this.bugattiImg, "bugatti.png");
        Funciones.scaleImage(this.lamboImg, "lambo.png");
        this.lambo_p1 = new Cola(1, "lambo");
        this.lambo_p2 = new Cola(2, "lambo");
        this.lambo_p3 = new Cola(3, "lambo");
        this.lambo_r = new Cola(4, "lambo");
        this.bugatti_p1 = new Cola(1, "bugatti");
        this.bugatti_p2 = new Cola(2, "bugatti");
        this.bugatti_p3 = new Cola(3, "bugatti");
        this.bugatti_r = new Cola(4, "bugatti");
        this.segundos = 10;
        this.mutex = new Semaphore(1);
        Administrador admin = new Administrador(this.mutex, this);
        IA ia = new IA(this.mutex, this);
        admin.start();
        ia.start();
    }
    
    public void pintarColas() {
        Vehiculo vehiculoLp1 = this.lambo_p1.readHead();
        Vehiculo vehiculoLp2 = this.lambo_p2.readHead();
        Vehiculo vehiculoLp3 = this.lambo_p3.readHead();
        Vehiculo vehiculoLr = this.lambo_r.readHead();
        
        String colaLp1 = "";
        String colaLp2 = "";
        String colaLp3 = "";
        String colaLr = "";
        
        Vehiculo vehiculoBp1 = this.bugatti_p1.readHead();
        Vehiculo vehiculoBp2 = this.bugatti_p2.readHead();
        Vehiculo vehiculoBp3 = this.bugatti_p3.readHead();
        Vehiculo vehiculoBr = this.bugatti_r.readHead();
        
        String colaBp1 = "";
        String colaBp2 = "";
        String colaBp3 = "";
        String colaBr = "";
        
        while (vehiculoLp1 != null) {
            if(colaLp1.equals("")) {
                colaLp1 = "L" + String.valueOf(vehiculoLp1.id);
            } else {
                colaLp1 = "L" + String.valueOf(vehiculoLp1.id) + "," + colaLp1;
            }
            vehiculoLp1 = vehiculoLp1.next;
        }
        while (vehiculoLp2 != null) {
            if(colaLp2.equals("")) {
                colaLp2 = "L" + String.valueOf(vehiculoLp2.id);
            } else {
                colaLp2 = "L" + String.valueOf(vehiculoLp2.id) + "," + colaLp2;
            }
            vehiculoLp2 = vehiculoLp2.next;
        }
        while (vehiculoLp3 != null) {
            if(colaLp3.equals("")) {
                colaLp3 = "L" + String.valueOf(vehiculoLp3.id);
            } else {
                colaLp3 = "L" + String.valueOf(vehiculoLp3.id) + "," + colaLp3;
            }
            vehiculoLp3 = vehiculoLp3.next;
        }
        while (vehiculoLr != null) {
            if(colaLr.equals("")) {
                colaLr = "L" + String.valueOf(vehiculoLr.id);
            } else {
                colaLr = "L" + String.valueOf(vehiculoLr.id) + "," + colaLr;
            }
            vehiculoLr = vehiculoLr.next;
        }
        while (vehiculoBp1 != null) {
            if(colaBp1.equals("")) {
                colaBp1 = "B" + String.valueOf(vehiculoBp1.id);
            } else {
                colaBp1 = "B" + String.valueOf(vehiculoBp1.id) + "," + colaBp1;
            }
            vehiculoBp1 = vehiculoBp1.next;
        }
        while (vehiculoBp2 != null) {
            if(colaBp2.equals("")) {
                colaBp2 = "B" + String.valueOf(vehiculoBp2.id);
            } else {
                colaBp2 = "B" + String.valueOf(vehiculoBp2.id) + "," + colaBp2;
            }
            vehiculoBp2 = vehiculoBp2.next;
        }
        while (vehiculoBp3 != null) {
            if(colaBp3.equals("")) {
                colaBp3 = "B" + String.valueOf(vehiculoBp3.id);
            } else {
                colaBp3 = "B" + String.valueOf(vehiculoBp3.id) + "," + colaBp3;
            }
            vehiculoBp3 = vehiculoBp3.next;
        }
        while (vehiculoBr != null) {
            if(colaBr.equals("")) {
                colaBr = "B" + String.valueOf(vehiculoBr.id); 
            } else {
                colaBr = "B" + String.valueOf(vehiculoBr.id) + "," + colaBr;
            }
            vehiculoBr = vehiculoBr.next;
        }
        
        this.lamboP1.setText(colaLp1);
        this.lamboP2.setText(colaLp2);
        this.lamboP3.setText(colaLp3);
        this.lamboR.setText(colaLr);
        
        this.bugattiP1.setText(colaBp1);
        this.bugattiP2.setText(colaBp2);
        this.bugattiP3.setText(colaBp3);
        this.bugattiR.setText(colaBr);
    }
}
